In [1]:
import polars

from qif_micro import model
from qif_micro import qif

_ = polars.Config.set_engine_affinity("streaming")

Consider the following dataset as an example:

In [2]:
dataset = {
    0: [
        {"payee": "Red Rooster", "description": "Chicken burger", "amount": 7.00},
        {"payee": "Clinic", "description": "Fertility treatment", "amount": 150.00}
    ],
    1: [{"payee": "Aldi", "description": "Groceries", "amount": 20.00}],
    2: [
        {"payee": "Uber", "description": "23 minutes trip", "amount": 20.00},
        {"payee": "Lakeside", "description": "One night", "amount": 50.00},
        {"payee": "Clinic", "description": "Skin cancer treatment", "amount": 150.00}
    ],
    3: [{"payee": "Uber", "description": "13 minutes trip", "amount": 15.00}],
    4: [{"payee": "Uber", "description": "15 minutes trip", "amount": 15.00}]
}

count_records = lambda i: len(dataset[i])
payees = [e["payee"] for r in dataset.values() for e in r]
descrs = [e["description"] for r in dataset.values() for e in r]
amounts = [e["amount"] for r in dataset.values() for e in r]

dataset = polars.DataFrame({
    "uid": [i for i in dataset for _ in range(count_records(i))],
    "payee": payees,
    "description": descrs,
    "amount": amounts
})

dataset

shape: (8, 4)
┌─────┬─────────────┬───────────────────────┬────────┐
│ uid ┆ payee       ┆ description           ┆ amount │
│ --- ┆ ---         ┆ ---                   ┆ ---    │
│ i64 ┆ str         ┆ str                   ┆ f64    │
╞═════╪═════════════╪═══════════════════════╪════════╡
│ 0   ┆ Red Rooster ┆ Chicken burger        ┆ 7.0    │
│ 0   ┆ Clinic      ┆ Fertility treatment   ┆ 150.0  │
│ 1   ┆ Aldi        ┆ Groceries             ┆ 20.0   │
│ 2   ┆ Uber        ┆ 23 minutes trip       ┆ 20.0   │
│ 2   ┆ Lakeside    ┆ One night             ┆ 50.0   │
│ 2   ┆ Clinic      ┆ Skin cancer treatment ┆ 150.0  │
│ 3   ┆ Uber        ┆ 13 minutes trip       ┆ 15.0   │
│ 4   ┆ Uber        ┆ 15 minutes trip       ┆ 15.0   │
└─────┴─────────────┴───────────────────────┴────────┘

Instead of sharing the raw microdata, 
we are interested in sharing the total amount spent and the number of transactions made by each customer:

In [3]:
sum_expr = polars.col("amount").sum()
count_expr = polars.col("amount").len()
dataset_agg = dataset.group_by("uid").agg(sum=sum_expr, count=count_expr).sort(by="uid")
dataset_agg

shape: (5, 3)
┌─────┬───────┬───────┐
│ uid ┆ sum   ┆ count │
│ --- ┆ ---   ┆ ---   │
│ i64 ┆ f64   ┆ u32   │
╞═════╪═══════╪═══════╡
│ 0   ┆ 157.0 ┆ 2     │
│ 1   ┆ 20.0  ┆ 1     │
│ 2   ┆ 220.0 ┆ 3     │
│ 3   ┆ 15.0  ┆ 1     │
│ 4   ┆ 15.0  ┆ 1     │
└─────┴───────┴───────┘

We then assume that the adversary knows the exact amount of one of a target's transactions,
and they want to infer the aggregated statistics of this target.

In [4]:
owner_attr = "uid"
count_attr = "count"
sum_attr = "sum"

prior, ch = model.agg_count_sum.build(dataset_agg, owner_attr, count_attr, sum_attr)

The adversary's knowledge about the target's total amount spent and number of transactions,
upon observing the aggregated data, is

In [5]:
prior.dist.sort(by=[count_attr, sum_attr]).collect()

shape: (4, 3)
┌───────┬───────┬─────┐
│ count ┆ sum   ┆ p   │
│ ---   ┆ ---   ┆ --- │
│ u32   ┆ f64   ┆ f64 │
╞═══════╪═══════╪═════╡
│ 1     ┆ 15.0  ┆ 0.4 │
│ 1     ┆ 20.0  ┆ 0.2 │
│ 2     ┆ 157.0 ┆ 0.2 │
│ 3     ┆ 220.0 ┆ 0.2 │
└───────┴───────┴─────┘

And the channel that models the correlation between each aggregated record and the possible auxiliary information is

In [6]:
def as_matrix(dist: polars.LazyFrame, count_attr, sum_attr, qid_attr) -> polars.LazyFrame:
    return (
        dist
        .collect()
        .sort(qid_attr)
        .pivot(on=qid_attr, index=[count_attr, sum_attr])
        .fill_null(0.0)
        .with_columns(**{count_attr: polars.col(count_attr).cast(int)})
        .sort(by=[count_attr, sum_attr])
    )

as_matrix(ch.dist, count_attr, sum_attr, "qid")

shape: (4, 223)
┌───────┬───────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ count ┆ sum   ┆ 0.0      ┆ 1.0      ┆ … ┆ 217.0    ┆ 218.0    ┆ 219.0    ┆ 220.0    │
│ ---   ┆ ---   ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ i64   ┆ f64   ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞═══════╪═══════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 1     ┆ 15.0  ┆ 0.0      ┆ 0.0      ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0      │
│ 1     ┆ 20.0  ┆ 0.0      ┆ 0.0      ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0      │
│ 2     ┆ 157.0 ┆ 0.006329 ┆ 0.006329 ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0      │
│ 3     ┆ 220.0 ┆ 0.009009 ┆ 0.008968 ┆ … ┆ 0.000163 ┆ 0.000122 ┆ 0.000082 ┆ 0.000041 │
└───────┴───────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

From the adversary's knowledge and the model above, 
we can get a joint distribution as follows:

In [7]:
joint = qif.push(prior, ch)
as_matrix(joint.dist, count_attr, sum_attr, "qid")

shape: (4, 223)
┌───────┬───────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ count ┆ sum   ┆ 0.0      ┆ 1.0      ┆ … ┆ 217.0    ┆ 218.0    ┆ 219.0    ┆ 220.0    │
│ ---   ┆ ---   ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ i64   ┆ f64   ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞═══════╪═══════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 1     ┆ 15.0  ┆ 0.0      ┆ 0.0      ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0      │
│ 1     ┆ 20.0  ┆ 0.0      ┆ 0.0      ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0      │
│ 2     ┆ 157.0 ┆ 0.001266 ┆ 0.001266 ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0      │
│ 3     ┆ 220.0 ┆ 0.001802 ┆ 0.001794 ┆ … ┆ 0.000033 ┆ 0.000024 ┆ 0.000016 ┆ 0.000008 │
└───────┴───────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

Now, the above is the joint correlation from the adversary's point of view,
but we have the actual data,
so we can construct a better correlation,
which we will then use to evaluate how well the adversary performs.

In [8]:
prior_baseline, ch_baseline = model.agg_count_sum.baseline(dataset, owner_attr, count_attr, sum_attr, "amount")
baseline = qif.push(prior_baseline, ch_baseline)
as_matrix(baseline.dist, count_attr, sum_attr, "amount")

shape: (4, 7)
┌───────┬───────┬─────┬──────┬──────────┬──────────┬──────────┐
│ count ┆ sum   ┆ 7.0 ┆ 15.0 ┆ 20.0     ┆ 50.0     ┆ 150.0    │
│ ---   ┆ ---   ┆ --- ┆ ---  ┆ ---      ┆ ---      ┆ ---      │
│ i64   ┆ f64   ┆ f64 ┆ f64  ┆ f64      ┆ f64      ┆ f64      │
╞═══════╪═══════╪═════╪══════╪══════════╪══════════╪══════════╡
│ 1     ┆ 15.0  ┆ 0.0 ┆ 0.4  ┆ 0.0      ┆ 0.0      ┆ 0.0      │
│ 1     ┆ 20.0  ┆ 0.0 ┆ 0.0  ┆ 0.2      ┆ 0.0      ┆ 0.0      │
│ 2     ┆ 157.0 ┆ 0.1 ┆ 0.0  ┆ 0.0      ┆ 0.0      ┆ 0.1      │
│ 3     ┆ 220.0 ┆ 0.0 ┆ 0.0  ┆ 0.066667 ┆ 0.066667 ┆ 0.066667 │
└───────┴───────┴─────┴──────┴──────────┴──────────┴──────────┘

Notice that, despite the fact that from the adversary's point of view lots of amount values seemed possible,
most of them in practice would never be part of the adversary's auxiliary information.
With this we can compute the adversary's expected chance of success as

In [9]:
f"{qif.posterior(prior, ch, baseline) * 100}%"

'76.66666666666666%'

Had we decided to share the raw microdata, the adversary's chance of success would be

In [10]:
f"{qif.posterior(prior_baseline, ch_baseline, baseline) * 100}%"

'86.66666666666666%'

Notice that what impacts the adversary's expected chance of success is the case when the auxiliary information is 7.00,
since, instead of inferring that the target's record is (count = 2, sum = 157.00),
the adversary is tricked into guessing (count = 3, sum = 220.00).